### ISSUE TITLE
Handling #hashtag and @mention tap within table view's cell for row delegate

### ISSUE THREAD

**Issue by brahmasys** [rinov/RegeributedTextView#1]
Hi,
First of all thank you for this useful project. I am using it in my app where there is a table view which show list of comment and every row may have @mention #hashtag. My issue is how to handle tap on these #hashtag and @mention to get the word which was tapped in table view cell itself. The RegeributedTextViewDelegate is there in ur project for this task, but its not getting called in my view controller.

here is my code in cell for row of table view delegate.:-

cell.txtComment.text = (dict.value(forKey: "component") as! String)

  
     cell.txtComment.addAttribute(.mention, attribute: .textColor(.red))
           

    cell.txtComment.addAttribute(.hashTag, attribute: .textColor(.red)) 

Thanks in advance.

**Comment by rinov** [comment]
Hi, @Rakesh33888.
I tried the same, it will work for me. 
Have you enabled `User Interaction Enabled` in your UITableViewCell and substitute `delegate`?
If you had already done that, please tell me  more detail about your UITableViewDataSource and custom UITableViewCell.

here is the example code in my UIViewController.
```swift
extension ViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: "CELL", for: indexPath) as? CustomCell else {
            return UITableViewCell()
        }
        cell.commentTextView.delegate = self
        cell.commentTextView.text = "@rinov #test"
        cell.commentTextView.addAttribute(.mention, attribute: .textColor(.red))
        cell.commentTextView.addAttribute(.hashTag, attribute: .textColor(.blue))
        return cell
    }
}

extension ViewController: RegeributedTextViewDelegate {
    // Call when tapped the mention or hashtag.
    func regeributedTextView(_ textView: RegeributedTextView, didSelect text: String, values: [String : Any]) {
        print("Select = \(text)")
    }
}
```

**Comment by rinov** [comment]
This already looks like resolved, so i'd like to close this issue.
